[build]
builder = "railpack"
buildCommand = "cd api && npm install && npm run build && cd ../web && npm install && npm run build"

[deploy]
startCommand = "cd ./web && npx serve -s dist --listen $PORT"
